version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev

volumes:
  gradle_cache:
